# Generated by Django 5.1.2 on 2024-11-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address_line_1',
            new_name='address',
        ),
    ]
