# Generated by Django 5.1.2 on 2024-11-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_address_line_1_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default=123456789, max_length=15),
            preserve_default=False,
        ),
    ]
