# Generated by Django 5.1.2 on 2024-11-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact',
            new_name='contact_no',
        ),
    ]
