# Generated by Django 5.1.3 on 2024-11-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_contact_profile_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
