# Generated by Django 5.1.3 on 2024-11-09 17:02

from django.db import migrations, models
import zoneinfo


class Migration(migrations.Migration):
    TIMEZONES_CHOICES = [(tz, tz) for tz in zoneinfo.available_timezones()]

    dependencies = [
        ('account', '0008_alter_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(
                choices=TIMEZONES_CHOICES,
                default="UTC",
                max_length=50,
            ),
        )
    ]
