# Generated by Django 5.1.3 on 2024-11-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Team Lead', 'Team Lead'), ('Software Developer', 'Software Developer'), ('QA Engineer', 'QA Engineer'), ('UI/UX Designer', 'UI/UX Designer'), ('Business Analyst', 'Business Analyst')], max_length=30),
        ),
    ]
