# Generated by Django 5.1.1 on 2024-11-07 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_contact_profile_contact_no'),
        ('meeting', '0002_remove_meeting_time_zone_meeting_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to='account.profile'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meetings', to='account.profile'),
        ),
    ]
