# Generated by Django 5.1.1 on 2024-11-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='userid',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
